### ISSUE TITLE
Limit contributor list

### ISSUE THREAD

**Issue by fdciabdul** [akhilmhdh/contributors-readme-action#29] opened 2021-10-05 08:13 UTC
this is only showing 30 contributor list in Read me.md

i had 100+ contributors in my repo

**Comment by akhilmhdh** [comment] 2021-10-05 09:02
@fdciabdul  really. need to check whether github changed there api limit default value.

**Comment by akhilmhdh** [comment] 2021-10-05 09:04
@fdciabdul  good catch indeed. The api has changed. Will make this patch soon, or feel free to open a PR
https://docs.github.com/en/rest/reference/repos?query=list+contributors#list-repository-contributors

**Comment by fdciabdul** [comment] 2021-10-05 09:25
> @fdciabdul good catch indeed. The api has changed. Will make this patch soon, or feel free to open a PR https://docs.github.com/en/rest/reference/repos?query=list+contributors#list-repository-contributors

right , see this one https://github.com/fdciabdul/Hacktoberfest-Indonesia-2021#kontributor-list

i think , the github api isn't limited that small , looking from https://github.com/lacolaco/contributors-img
that was showing 100+ contributors from github public API

**Comment by akhilmhdh** [comment] 2021-10-05 09:30
No no github api isn't limited at all. The issue is at the time of writing this action github api contributors list had no pagination.
Rather it showed 500 contributors list.

Now they have changed with default as 30 and pagination is included. I need to make a change in loading up contributors list by fetching all from paginated one

**Comment by akhilmhdh** [comment] 2021-10-05 09:31
Ill patch this by today

**Comment by akhilmhdh** [comment] 2021-10-05 19:46
@fdciabdul Hey there i have released the patch [contributors-readme-action@v2.2.1](https://github.com/marketplace/actions/contribute-list). It will solve your pagination and will list all users.

Thank you so much putting this issue and for using my action. Loved to get more feedback from users. Closing this issue for now, as i feel it's solved. Feel free to open it again if it doesn't solve.

Kindly give a ⭐ if you liked this action and also to get future updates. 😃

**Closed by akhilmhdh** 2021-10-05 19:46 UTC
Labels: bug, hacktoberfest
