### ISSUE TITLE
Can I use the user name instead of the name?

### ISSUE THREAD

**Issue by LorhanSohaky** [akhilmhdh/contributors-readme-action#26] opened 2021-05-25 19:30 UTC

**Comment by akhilmhdh** [comment] 2021-05-25 20:01
Hi @LorhanSohaky ,
Did u mean as the title under the image as username.

**Comment by LorhanSohaky** [comment] 2021-05-27 00:44
Exactly! For example my full name is Lorhan Sohaky and my username (login name) is LorhanSohaky

In the [Brasil API](https://github.com/BrasilAPI/BrasilAPI/) project we used this pattern and I would like to use your action in it.

- [issue](https://github.com/BrasilAPI/BrasilAPI/issues/302)
- [pr](https://github.com/BrasilAPI/BrasilAPI/pull/314)

**Comment by akhilmhdh** [comment] 2021-05-27 07:40
@LorhanSohaky ohhh wow. Awesome. 

I'll try to add this config during weekend. Also if u want to, feel free to open a PR.

**Comment by LorhanSohaky** [comment] 2021-05-27 12:41
Thanks! 

I see on the weekend can take to add the feature to not show a person in contribuidore list

**Comment by FDiskas** [comment] 2021-06-26 18:09
Yes please - missing the feature remove something from the list.

**Comment by akhilmhdh** [comment] 2021-06-26 18:17
Damn. I am so sorry. I was planning to work on this. But currently my exams are going on. So haven't got the time to include this feature. Although some parts needs to be changed this feature will come out as -<username> to remove a user. 

But the issue is haven't got the time to get into this. Let me see if I can make this release by this week.

Thank you your feedback. Really glad  to hear users purpose and ways to improve this action.

**Comment by akhilmhdh** [comment] 2021-07-17 18:01
Hey @LorhanSohaky  @FDiskas . Sorry for the delay. But good news. 😄 

contributors-readme-actionv2.2 has been released. It has the option to add use_username to the config to use that. Also introduced operators. Currently operator `-` can be used to remove a person from list. Kindly read the Readme.md. 

Also the order is given importance so to remove a user properly, kindly add at last. 

Closing the issue. Feel free to open it, if there are any issue regarding , or new one for another awesome features. Planning to add more operators for the action. 

Kindly give a ⭐ if you liked this action and also to get future updates. 😃

**Closed by akhilmhdh** 2021-07-17 18:01 UTC

**Comment by akhilmhdh** [comment] 2021-07-17 18:04
Adding an example to avoid confusion
```bash
<!-- readme: contributors,akhilmhdh/- -start -->
<!-- readme: contributors,akhilmhdh/- -end -->
```
This removes `akhilmhdh` from the list.

**Comment by FDiskas** [comment] 2021-07-17 19:47
That's a supper great news. Thanks for this feature.

**Comment by LorhanSohaky** [comment] 2021-07-21 12:06
Thank you very much!!!
I tried to change it, but the REGEX were complicated for me to understand

**Comment by akhilmhdh** [comment] 2021-07-21 17:36
@LorhanSohaky So sorry for that. I think I should improve my documentation. I give a great importance on my code quality. Ill definitely look into adding better internal doc to improve code readability. 

Regex was a choice I had to make, because given the parsing and also all the corner cases, JS split was a not good one.
